name: jsmn
description: 超轻量级的 C 语言 json 解析库
keywords:                                      # 多标签
  - base
  - JSON
author:
  name: chuwang
  email: chuwang@xxxx.com
license: Apache license v2.0                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

depends:                                       # 该组件依赖其他的组件
  - libc

build_config:
  include:
    - include
  cflag: ''                             # C 编译器所需要要的编译参数
  cxxflag: ''                         # CXX 编译器所需要要的编译参数
  asmflag: ''                            # 汇编器所需要要参数
  # define:                                      # 宏定义
    # - CONFIG_XXX
    # - CONFIG_AAA
    # - CONFIG_BBB
    # - XXX=1024

source_file:
  - "src/*.c"                                      # 支持通配符与正则表达示

install:
  - dest: "include/"
    source:
      - include/jsmn.h
